// AUTO GENERATED FILE - DO NOT MODIFY
#include "stdafx.h"
// stdafx.h must be first
#include "main.h"
sym keywords [] = {
{0,"T"},
{0,"V"},
{0,"ceiling"},
{0,"cnf"},
{0,"conjecture"},
{0,"difference"},
{0,"dimacs"},
{0,"distinct"},
{0,"false"},
{0,"floor"},
{0,"fof"},
{0,"greater"},
{0,"greatereq"},
{0,"h"},
{0,"help"},
{0,"i"},
{0,"include"},
{0,"int"},
{0,"is_int"},
{0,"is_rat"},
{0,"ite"},
{0,"less"},
{0,"lesseq"},
{0,"lst"},
{0,"o"},
{0,"product"},
{0,"quotient"},
{0,"quotient_e"},
{0,"quotient_f"},
{0,"quotient_t"},
{0,"rat"},
{0,"real"},
{0,"remainder_e"},
{0,"remainder_f"},
{0,"remainder_t"},
{0,"round"},
{0,"sum"},
{0,"t"},
{0,"tType"},
{0,"tff"},
{0,"to_int"},
{0,"to_rat"},
{0,"to_real"},
{0,"tptp"},
{0,"true"},
{0,"truncate"},
{0,"type"},
{0,"uminus"},
{0,"v"},
{0,"version"},
};
